# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: 2696f9ae94b0cdfe15fc
    multiple: false
    tabs: 'facebook file'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Σελίδες'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/home.md'
        label: 'Αρχική'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Τιτλος, name: heroTitle, widget: string, required: true }
          - {
              label: Υποτιτλος,
              name: heroSubtitle,
              widget: string,
              required: false,
            }
          - { label: Εισαγωγικος τιτλος, name: introTitle, widget: string }
          - { label: Εισαγωγικο κειμενο, name: introSubtitle, widget: markdown }
          - label: 'Στατιστικά'
            name: 'intro'
            widget: 'list'
            fields:
              - {
                  name: title,
                  label: Νουμερο,
                  widget: string,
                  default: '',
                  required: false,
                }
              - {
                  name: description,
                  label: Κειμενο,
                  widget: string,
                  required: false,
                }
          - { label: Φωτογραφιες τιτλος, name: galleryTitle, widget: string }
          - label: 'Φωτογραφιες'
            name: 'gallery'
            widget: 'list'
            fields:
              - { name: image, label: Εικονα, widget: image }
              - {
                  name: title,
                  label: Τιτλος εικονας,
                  widget: string,
                  required: false,
                }
              - {
                  name: alt,
                  label: Εναλλακτικο κειμενο εικονας,
                  widget: string,
                }
          - { label: Υπηρεσιες τιτλος, name: accordionTitle, widget: string }
          - label: 'Υπηρεσιες'
            name: 'accordion'
            widget: 'list'
            fields:
              - { name: title, label: Υπηρεσια, widget: string, default: '' }
              - {
                  name: description,
                  label: Περιγραφη υπηρεσιας,
                  widget: markdown,
                }
          - { label: Body, name: body, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Τιτλος, name: title, widget: string, required: false }
              - {
                  label: Περιγραφη,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/blog.md'
        label: 'Δουλειές'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/contact.md'
        label: 'Επικοινωνία'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Τιτλος, name: title, widget: string }
          - { label: Υποτιτλος, name: subtitle, widget: string }
          - {
              label: Εικονα,
              name: heroImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Τηλεφωνο, name: phone, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Διευθυνση, name: address, widget: text }
          - { label: Email, name: email, widget: string }
          - { label: Body, name: body, widget: markdown }
          - name: locations
            label: Τοποθεσιες
            widget: list
            fields:
              - {
                  name: mapLink,
                  label: mapLink,
                  widget: string,
                  required: false,
                  default: '',
                }
              - {
                  name: lat,
                  label: latitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
              - {
                  name: lng,
                  label: longitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

  - name: posts
    label: Έργα
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Τιτλος, name: title, widget: string }
      - {
          label: Μινι εικονα,
          name: featuredImage,
          widget: image,
          required: true,
        }
      - label: 'Φωτογραφιες'
        name: 'gallery'
        widget: 'list'
        fields:
          - { name: image, label: Εικονα, widget: image }
          - {
              name: title,
              label: Τιτλος εικονας,
              widget: string,
              required: false,
            }
          - { name: alt, label: Εναλλακτικο κειμενο εικονας, widget: string }
      - label: 'Κατηγοριες'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Κατηγορια'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
      - { label: Date / Order, name: date, widget: date, format: 'YYYY-MM-DD' }
      - { label: Content, name: body, widget: markdown }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: postCategories
    label: Κατηγορίες
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: BlogIndex }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }
  - name: infoPages
    label: Μπλογκ
    editor:
      preview: true
    folder: content/infoPages
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: DefaultPage,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Τιτλος, name: heroTitle, widget: string }
      - { label: Υποτιτλος, name: heroSubtitle, widget: string }
      - { label: Εικονα, name: heroImage, widget: image }
      - { label: Κειμενο, name: body, widget: markdown }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
